# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 01:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160225_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 26, 1, 41, 39, 355929, tzinfo=utc), verbose_name='data created'),
            preserve_default=False,
        ),
    ]
