# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_review_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
